package com.zendapag.core.entity.enums;

public enum WebhookEventType {
    PAYMENT_CREATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    PAYMENT_CANCELLED,
    SETTLEMENT_COMPLETED,
    WITHDRAWAL_COMPLETED,
    WITHDRAWAL_FAILED,
    DISPUTE_CREATED,
    DISPUTE_RESOLVED,
    KYC_VERIFICATION_REQUIRED,
    KYC_VERIFICATION_COMPLETED
}
